### ISSUE TITLE
Windows server deleting track on restart

### ISSUE THREAD

**Issue by rchpi87** [swing-opensource/swingmusic#122]
When restarting the application the app loads the tracks,albums,album colors and artists then the next step is removing deleted tracks which are all the tracks it loaded in the first place.
Windows server 2019 

<img width="972" alt="Screenshot 2023-04-26 at 10 53 20 AM" src="https://user-images.githubusercontent.com/45955788/234616038-13c7df76-bc49-40b2-a190-a5a77f225aa0.png">

**Comment by mungai-njoroge** [comment]
Hello @rchpi87 

Thanks for raising this issue. I think this is a miscommunication mistake. The app actually checks whether each of the tracks loaded still exists. It removes deleted tracks from the database.

So I think the text there should read something like: `Checking for deleted tracks` or something ... instead of `Removing deleted tracks`. If  you have any suggestions please let me know.

Thank you.

**Comment by rchpi87** [comment]
No that makes perfect sense. I absolutely love this software please keep up the good work !!

**Comment by mungai-njoroge** [comment]
Hello @rchpi87 

Seems like you have quite a large library. This project is pretty much young, and some features might not work as expected. Please feel free to open an issue if you encounter bugs, or if you have suggestions or feature requests.

Thank you.
