### ISSUE TITLE
Revamped Home/Landing Page

### ISSUE THREAD

**Issue by gerryflux** [swing-opensource/swingmusic#128]
The current landing page with user's music folders could be reworked.

In most cases, people have music buried in multiple folders and only use software such as this not to view folders but all their music in one place in a more structured manner.

This app so far does that, and to make for an even more immersive experience and match the vision you have for the app, the home/landing page could instead look like what Apple Music does or even [this](https://dribbble.com/shots/16741029-Music-Streaming-Web-App) - I find the design language similar too.

I imagine the page being scrollable with sections like:

- **Mixes Inspired By:** This could be an auto-curated playlist based on user playback history or a random song just as Plexamp does with its "[Sonic Analysis"](https://techcrunch.com/2021/08/12/plexs-new-feature-matches-your-sonically-similar-music-to-make-playlists/) 
- **Genre Mixes:** Self-explanatory. e.g Pop, Hip-Hop, Metal, Amapiano, etc.
- **Because you like...:** Another way to recommend songs from other similar artists based on what the user has favourited or played often.

They could each have say 4 medium sized or 2 large size cards per section, it would beautifully fit perfectly on the home page.

**Comment by mungai-njoroge** [comment]
Hello @gerryflux 

Sorry for the lack of a homepage. There's no homepage at the moment because there's no data to show ... let me explain.

I agree with and share your vision of the homepage. However, all the features that collect and process the data needed by the homepage are not developed yet. For example, to be able to create mixes, you need to record all the music played and then analyze it to create mixes. Currently, the app does not do that. So I decided instead of showing a boring homepage that just shows you random things, I build the necessary features first. 

At the moment, I'm focusing on building the basic features that are required in a typical music player. Like volume controls, etc. You can check the Todo here: https://rhetorical-othnielia-565.notion.site/Next-release-TODO-A-wishlist-ff6df76a7dbc4d5c8fd2f9437641055a?pvs=4

I'm the only maintainer for this project, so pushing things is slow.

Thank you for understanding.
