### ISSUE TITLE
Frontend CPU usage too high

### ISSUE THREAD

**Issue by kja999** [swing-opensource/swingmusic#144]
Hi,
Happy to have this disputed as it's been hard to clarify. 
I use swing to play music on my TV, and very rapidly the frontend becomes unusable and unresponsive.
Typical actions, browse to album, play, browse back to main folder (10k tracks in folders by artist), go to album. Navigate back to folders and everything locks up.

I run the backend on docker, and can see there is no specific increase in the server load. Running the client on a laptop though shows significant CPU usage at the point where everything locks up (i5-8265 hits 26% usage).
I think this is the issue on a frontend where the CPU isn't so powerful (like a TV).

Is there a way to lower the impact ?

**Comment by mungai-njoroge** [comment]
Hello @kja999 

Thanks for opening this issue. There was a bug in the artist page that caused it to fetch all artist albums instead of only enough to fit the viewport. If an artist has a lot of albums, the page you navigate to next, will be slow. I fixed this bug in the upcoming release `v1.3.0`.

If you want to test out the beta, you can pull [this](https://hub.docker.com/layers/geoffrey45/swingmusic.v1.3.0.beta/kja999/images/sha256-777fd8d96bc9637554b9e4e581c84e686059d249298be299de42ae3dd6f7f676?context=repo) docker image tag created just for you. Please provide feedback on the new release.

```sh
docker pull geoffrey45/swingmusic.v1.3.0.beta:kja999
```

```sh
docker run --name swingmusicv130beta -p 1970:1970 \
  -v /path/to/music:/music \
  -v /path/to/config:/config \
  --restart unless-stopped \
  geoffrey45/swingmusic.v1.3.0.beta:kja999
```

Replace `/path/to/music` with your music folder path and `/path/to/config` with where the config folder should be created.

Let me know whether this makes things better.

**Comment by kja999** [comment]
Hi,
I had a try through yesterday but no improvement. All seems well for the first 10 minutes but slowly stops responding.
This time I also notice the play timer also stops when it runs slow (music keeps playing), so a sudden jump from 0:03 to 0:43 for example.
Possibly the resources required are just too high for non-pc hardware

**Comment by mungai-njoroge** [comment]
@kja999  

I checked the memory usage on the browser and it seems like the usage is normal ~100mb. The CPU usage spikes ups sometimes but I don't think there's anything we can do at the moment.

**Comment by kja999** [comment]
Thanks. I'll keep trying to work out if there is anything I can find too. It's only an issue on TV, not other devices
