### ISSUE TITLE
Large files like FLAC not supported?

### ISSUE THREAD

**Issue by penguinway** [swing-opensource/swingmusic#145]
Hi,
I like your product very much, but I found that when importing some larger files, for example, the playback of my lossless FLAC format music is not supported. What is going on?
This is a photo when it going wrong.
![wrong](http://image.penguinway.space/i/2023/09/23/650ea610b9635.png)
And it the big of this music file.
![big](http://image.penguinway.space/i/2023/09/23/650ea6d3d87af.png)
Can you tell me why?If it is because it is not supported for the time being, I hope to add support as soon as possible.

Thank you very much!
Good luck with your development!

**Comment by penguinway** [comment]
And the other FLAC files is OK,only the biggest can not play,I will test more bigger file.

**Comment by penguinway** [comment]
> 其他FLAC文件都可以，只有最大的不能播放，我会测试更大的文件。

Right,it seems that the FLAC files which bigger than 40Mb cannot play.

**Comment by mungai-njoroge** [comment]
Hello @penguinway 

Thank for this issue. I don't think it's a problem with the size (I have ~140mb FLACs and they're playing fine). I think it might be a problem with the file itself somehow, maybe not encoded properly or something. Can you try opening the said file in the browser directly from your file manager.

`Right click on file -> open with -> your browser`

If the file file plays there, then we can try to figure out the problem from there. If the file downloads itself, then the browser is not able to open it as audio.

Let me know how it goes.

**Comment by penguinway** [comment]
OK,I open it with my browser,it plays no problem.This file was not recognized as a download in the browser.

**Comment by penguinway** [comment]
Oh,I tried running the binary directly in linux and now it's ok :) (I was using docker containers before), maybe it's because of some issues with docker containers (lol, I think you should probably look into what's possible in docker containers problems?)
Once again, I wish you smooth development!
I love your products!

**Comment by mungai-njoroge** [comment]
@penguinway 

Glad to hear you found a way to make it work. I'm currently winding up on a new release `v1.3.0`. Lots of new features. I've also modified the Docker image to just use the linux binary instead of building it.

I'll publish the Docker image on Docker hub to make it easier to work with. You can watch the repo to be notified of the release from Github.

If you wanna try out the beta, just hit me ... with your favorite song 😅 and I'll do a build for you 😸.

**Comment by penguinway** [comment]
@mungai-njoroge 
I very much hope you can launch your **v1.3.0** smoothly, I believe it will be an exciting project.
And sure,I would like to share my favorite song with you!My favortie song is George Winston's "Variations On The Canon By Pachelbel". Enjoy it! And hope you have a good day!
I can't wait to see your **v1.3.0**!
Thank you!

**Comment by penguinway** [comment]
I'm looking forward to future improvements and features and maybe will definitely be a supporter.

**Comment by penguinway** [comment]
Thanks for your help. I'm looking forward to future improvements and features and maybe will definitely be a supporter.😄

**Comment by penguinway** [comment]
I'm looking forward to future improvements and features and maybe will definitely be a supporter.😄

**Comment by mungai-njoroge** [comment]
@penguinway  

Thanks for the music. I'm also excited to hear that you will be a supporter. I'm working on a way to accept donations and it will be available on the revamped website once `v1.3.0` lands.

[Here](https://hub.docker.com/layers/geoffrey45/swingmusic.v1.3.0.beta/penguinway/images/sha256-b78e40e53741fddb93376e48411d677e2f822b1c320ec840b53365fd87770f5e?context=repo)'s your Docker build. Pull and run it to try out the beta.

```sh
docker pull geoffrey45/swingmusic.v1.3.0.beta:penguinway
```

```sh
docker run --name swingmusicv130beta -p 1970:1970 \ 
  -v /path/to/music:/music \
  -v /path/to/config:/config \
  --restart unless-stopped \
  geoffrey45/swingmusic.v1.3.0.beta:penguinway
```

Replace `path/to/music` with your music directory and `path/to/config` to where you want the config folder to be created.

Please let me know if anything seems not to be working correctly. I'd like to hear what you think about it in general.

Enjoy ... and thanks.

**Comment by penguinway** [comment]
@mungai-njoroge 
A very stunning version, Love comes from China! Not only did it perfectly solve my previous problem, but I also like the UI of ` v1.3.0 `very much! It's so beautiful!
Thank you for the Docker image!
I hope you can develop better versions in the future, and I will always support your projects!

**Comment by mungai-njoroge** [comment]
Hello @penguinway  

The new release is out. You can pull the latest docker image from Github Packages ([see Readme](https://github.com/swing-opensource/swingmusic#docker)). If you'd like to donate, visit the [support us page](https://swingmusic.vercel.app/support-us.html).

### Changelog since previous beta (geoffrey45/swingmusic.v1.3.0.beta:penguinway)

- Join EP & Singles in artist page
- Make artist page faster (removed 100+ lines of 💩 code)
- Make artist page with many albums faster
  (rewrite logic for calculating album dates to improve time complexity)
- Show newly created playlist in playlist list page
- TTY progress bars look a tiny bit consistent

### Bug fixes

- Playlist with no tracks breaking playlist page
- Artist discography page not working
- Albums with no tracks missing from that album artist page
- Ed Sheeran tracks being in a single album (due to their album names being only one non-alpha-numeric character ... fuck Ed Sheeran) you might lose some favorites
- Some soundtrack albums being labeled as normal albums in album page
- Incorrect text balancing on playlist page header using a square image
- Merging albums not working

**Comment by penguinway** [comment]
@mungai-njoroge 
OK,I will get it! Thank you very much!
