### ISSUE TITLE
Search only returns one of two results

### ISSUE THREAD

**Issue by Coding-Kiwi** [swing-opensource/swingmusic#152]
I have two songs

![image](https://github.com/swing-opensource/swingmusic/assets/5007641/4ba4e166-5b04-4b5c-a5e9-bf129740d28c)

"Hour of Hollow Knight Ambience For Relaxing & Studying" and "2h Hollow Knight Ambience"

When I search for hollow only one shows up

/#/search/top?q=hollow

![image](https://github.com/swing-opensource/swingmusic/assets/5007641/4447a92d-ca69-47e3-8bda-57e3907e47aa)

only when I search for "hollow kn" both show up

/#/search/top?q=hollow+kn

![image](https://github.com/swing-opensource/swingmusic/assets/5007641/92368f97-3eb1-4db2-bd05-8329e97d4568)

awesome app btw :)

**Comment by mungai-njoroge** [comment]
@Coding-Kiwi 

Thanks for using Swing Music. The fuzzy search feature is powered by a third-party search package ([rapidfuzz](https://github.com/maxbachmann/RapidFuzz)) which does not work veeery well with music data.

It's an issues that has been bugging me for some time, so I will fix it in the future. It's however not a priority because there are other more important things to fix and build at the moment.
